runtime: python39
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  MONGO_URI: 'mongodb+srv://tester:giatri@clustertest.kmzw0bd.mongodb.net/?retryWrites=true&w=majority'
  GOOGLE_APPLICATION_CREDENTIALS: 'C:\Users\Giatri Lalla\Desktop\Swayed\api_key.json'

runtime_config:
  python_version: 3.9

handlers:
- url: /.*
  script: auto
